if(instance_exists(_inst)){
   instance_destroy(_inst);
}
if(surface_exists(_hold_ring_surface)){
	surface_free(_hold_ring_surface);
	_hold_ring_surface=-1;
}
if(surface_exists(_surface_ui)){
	surface_free(_surface_ui);
	_surface_ui=-1;
}
