Battle_SetEnemyName(_enemy_slot,Lang_GetString("battle.enemy.test.0.name"))
Battle_SetEnemyActionNumber(_enemy_slot,4)
Battle_SetEnemyActionName(_enemy_slot,0,Lang_GetString("battle.enemy.test.0.action.0"))
Battle_SetEnemyActionName(_enemy_slot,1,Lang_GetString("battle.enemy.test.0.action.1"))
Battle_SetEnemyActionName(_enemy_slot,2,Lang_GetString("battle.enemy.test.0.action.2"))
Battle_SetEnemyActionName(_enemy_slot,3,Lang_GetString("battle.enemy.test.0.action.3"))

Battle_SetEnemyDEF(_enemy_slot,0)
Battle_SetFleeableOverride(1)
Battle_SetMenuDialogCandidateEnabled(1)